feat/scb-525: implement native ad slots replacing nativo on article pages
newsuk/times-components pull request #2648
Opened 2020-10-02 08:07 UTC by nikkibyrne

2020-10-02 09:49 UTC, mikefieldmay requested changes
A couple of changes to keep it in line with our codebase.
Might be worth thinking about what happens to the div if the use has ad blocker or things along those lines. Maybe don't display and use the ad library to display when the ads have loaded

2020-10-02 09:49 UTC, mikefieldmay commented on packages/article-skeleton/src/native-ad.web.js
> +	const nativeAd = paywallChildren.find(item => item.name === 'nativeAd');
We're adding the nativeAd ourselves right? Not quite sure what the check is for?

2020-10-02 09:49 UTC, mikefieldmay commented on packages/article-skeleton/src/native-ad.web.js
> +	let paraCount = 0;
We tend to use `const` values instead of lets so that we aren't mutating the value and it's easier to read.

```suggestion
	const paragraphItems = paywallChildren.map((item, index) => ({...item, index})).filter(item => item.name === 'paywall')
	const indexToAdd = paragraphItems[6] ? item.index : null
```

2020-10-02 09:49 UTC, mikefieldmay commented on packages/article-skeleton/src/native-ad.web.js
> +	const clonedChildren = [...children];
I would move this to line 2 and then do 
```suggestion
	const child = clonedChildren.find(item => item.name === 'paywall');
	if (!child) {
    return clonedChildren;
  }
```

2020-10-02 09:49 UTC, mikefieldmay commented on packages/article-skeleton/src/article-body/article-body.web.js
> +      <NativeAd key={key}>
Do we need an ID on this block?
What happens if the user is using add block or something like that?
It may be worth setting this div to display none initially and to then change that in the ad library if the ads load?

2020-10-02 09:49 UTC, mikefieldmay commented on packages/article-skeleton/__tests__/web/native-ad.web.test.js
> +		const content = [
```suggestion
		const content = [
		{
				name: 'paywall',
				children: []
			}]
```

2020-10-02 09:49 UTC, mikefieldmay commented on packages/article-skeleton/__tests__/web/native-ad.web.test.js
> +	test('Checks nativeAd does not already exist and that Paywall does exist', () => {
```suggestion
	it('does not insert ad if less than 7 paragraphs in paywall', () => {
```

2020-10-02 09:49 UTC, mikefieldmay commented on packages/article-skeleton/__tests__/web/native-ad.web.test.js
> +		expect(content).toEqual(
This seems to be asserting against the object you created above without running the `insertNativeAd` on it>?
Maybe: 
```
const contentWithoutParagraphs = [
		{
				name: 'paywall',
				children: []
			}
]

expect(insertNativeAd(content)).toEqual(content)
```

2020-10-02 09:49 UTC, mikefieldmay commented on packages/article-skeleton/__tests__/web/native-ad.web.test.js
> +		);
I would add a third test where if paywall doesn't exist the original content is just returned returned

2020-10-02 09:49 UTC, mikefieldmay commented on packages/article-skeleton/src/native-ad.web.js
> +	let paraCount = 0;
Array indexes start at 0, so the seventh paragraph element should be at position 6?

2020-10-14 14:22 UTC, mikefieldmay commented on packages/article-skeleton/src/native-ad.web.js
> +	const child = children.find(item => item.name === 'paywall');
this should be:
```suggestion
	const child = clonedChildren.find(item => item.name === 'paywall');
```

2020-10-20 11:24 UTC, nikkibyrne commented on packages/article-skeleton/src/native-ad.web.js
> +	let paraCount = 0;
have updated

2020-10-20 11:24 UTC, nikkibyrne commented on packages/article-skeleton/src/native-ad.web.js
> +	const clonedChildren = [...children];
has been updated

2020-10-20 11:25 UTC, nikkibyrne commented on packages/article-skeleton/src/article-body/article-body.web.js
> +      <NativeAd key={key}>
have added a class for the hidden styling

2020-10-20 11:25 UTC, nikkibyrne commented on packages/article-skeleton/__tests__/web/native-ad.web.test.js
> +		);
Have added an extra test for the paywall

2020-10-27 12:30 UTC, mikefieldmay approved these changes

2020-10-27 14:51 UTC, merged