feat(TE-6): algolia related articles
newsuk/times-components pull request #2686
Opened 2021-04-21 14:32 UTC by flashcheeks

Algolia provider gets related articles for a given article page

2021-04-23 13:31 UTC, flashcheeks commented on packages/utils/src/algolia-related-articles.web.js
> +    console.log("searchRelatedArticles", query); // eslint-disable-line no-console
`console.log` will be used in production (behind feature flag) to view Aloglia query.

2021-04-23 13:34 UTC, flashcheeks commented on packages/utils/src/algolia-search.web.js
> +const indexName = "prod_articles_by_published_date_desc";
I did want to store these values as `process.env` but they seem to exist in [cps-content-render](https://github.com/newsuk/cps-content-render/blob/develop/packages/render/src/config/prod.json#L40) so they are probably fine to exist here.

2021-04-23 16:41 UTC, flashcheeks commented on packages/utils/src/algolia-related-articles.web.js
> +    console.log("AlgoliaSearch query", query); // eslint-disable-line no-console
console.log will be used in production (behind feature flag) to view Aloglia query.

2021-04-27 08:45 UTC, mikefieldmay requested changes
everything looks good, but I'm not sure about storing any keys in the code as Times Components is a public repo

2021-04-27 08:45 UTC, mikefieldmay commented on packages/utils/src/algolia-search.web.js
> +const indexName = "prod_articles_by_published_date_desc";
My only concern with this is that render is a private repo where theoretically times components is open to the public

2021-04-27 08:46 UTC, flashcheeks commented
> everything looks good, but I'm not sure about storing any keys in the code as Times Components is a public repo

Good point, I will remove

2021-04-28 09:36 UTC, mikefieldmay approved these changes

2021-04-28 11:03 UTC, merged