feat(TE-43): Typescript in article puffs
newsuk/times-components pull request #2692
Opened 2021-05-04 11:01 UTC by bibicollins1

2021-05-05 14:08 UTC, vinhlam approved these changes
happy for you to not fix these as i can do them in my PR

2021-05-05 14:08 UTC, vinhlam commented on packages/ts-components/src/__tests__/ViewCountWrapper.test.tsx
> + * @jest-environment jsdom
this no longer require as we added it to one of the config files

2021-05-05 14:08 UTC, vinhlam commented on packages/ts-components/src/in-article-puff/styles.ts
> +  align-items: top;
`top` is not a valid value for align-items, its been complaining in my IDE

2021-05-05 15:55 UTC, flashcheeks requested changes

2021-05-05 15:55 UTC, flashcheeks commented on packages/ts-components/CHANGELOG.md
> +# Change Log
We should delete this file.

2021-05-05 15:55 UTC, flashcheeks commented on packages/ts-components/README.md
> +# @times-components/responsive-image
We should update this file with relevant info/commands to help explain the components and example usage.

2021-05-05 15:55 UTC, flashcheeks commented on packages/ts-components/package.json
> +    "react-native": "0.61.5",
Do we need native libraries?

2021-05-05 15:55 UTC, flashcheeks commented on packages/ts-components/tsconfig.json
> +    "jsx": "react-native",
Should this be `react`?

2021-05-05 15:55 UTC, flashcheeks commented on packages/article-skeleton/src/article-body/article-body.web.js
> +          <InArticlePuff
Looking at the current/old `in-article-puff` component I can see that it receives some props but also loads data from an external .json file (receives id then loads `image`, `copy`, `url` etc).

It is probably worth us chatting about our desired data approach.

2021-05-05 17:13 UTC, bibicollins1 commented on packages/ts-components/package.json
> +    "react-native": "0.61.5",
@vinhlam

2021-05-06 12:06 UTC, vinhlam commented on packages/ts-components/package.json
> +    "react-native": "0.61.5",
Ill have a check to see if it causes any issues

2021-05-06 12:48 UTC, vinhlam commented on packages/ts-components/CHANGELOG.md
> +# Change Log
does it not automatically get generated when there are changes and version updates?

2021-05-06 14:29 UTC, vinhlam commented on packages/ts-components/package.json
> +    "react-native": "0.61.5",
I can remove it from the dependences and the babel config but if I try to do any `yarn add` it complains. I've removed it, and it builds and passes all tests

2021-05-13 15:18 UTC, flashcheeks approved these changes

2021-05-13 15:25 UTC, merged