Feat/TDP-121 Inarticle Bignumbers Analytics
newsuk/times-components pull request #2790
Opened 2021-09-07 06:56 UTC by Srinivasan-Ramasamy

Please review and suggest if we need to do any changes. Thank you.

2021-09-13 09:19 UTC, bibicollins1 requested changes
I don't see any analytics calls happening in the storybook, if you check the other components in the actions tab on the right you should be getting an object back called analytics-action which will contain the tracking. Maybe adding some tests for the tracking will help debug this

2021-09-13 09:19 UTC, bibicollins1 commented on packages/ts-components/src/components/in-article-big-numbers/__tests__/BigNumbers.test.tsx
> +  describe('tracking', () => {
This doesn't actually seem to be testing the analytics calls?

2021-09-13 09:45 UTC, Srinivasan-Ramasamy commented on packages/ts-components/src/components/in-article-big-numbers/__tests__/BigNumbers.test.tsx
> +  describe('tracking', () => {
Hi @bibicollins1, I've implemented the same way which other story implementation. Analytics call is happening Bibi. Please check this screen shot and please correct me is I'm wrong.


![Screenshot from 2021-09-13 15-11-59](https://user-images.githubusercontent.com/87307441/133062210-05569e11-c1e1-4cd6-9488-e6cdc635e4a7.png)
![Screenshot from 2021-09-13 15-12-16](https://user-images.githubusercontent.com/87307441/133062149-97cc99be-7a16-45bc-9d4d-6e6eda1de147.png)
![Screenshot from 2021-09-13 15-12-09](https://user-images.githubusercontent.com/87307441/133062191-610ea6e9-4d69-4fe2-8c5e-39c2ef49a9c8.png)

2021-09-13 09:52 UTC, bibicollins1 commented on packages/ts-components/src/components/in-article-big-numbers/__tests__/BigNumbers.test.tsx
> +  describe('tracking', () => {
Oh strange they weren't happening with mine when I ran it, will try again. Could we still get some tests for the tracking though? The describe block is tracking but I think we are only testing when you click read more button

2021-09-13 10:03 UTC, bibicollins1 commented on packages/ts-components/src/components/in-article-big-numbers/__tests__/BigNumbers.test.tsx
> +  describe('tracking', () => {
Resolved part of this with the analytics showing in storybook but could we still get some tests on the tracking as you have added a tracking describe block. I don't think click show all needs to be in the tracking describe block and can go back to where it was before.

2021-09-13 10:59 UTC, Srinivasan-Ramasamy commented on packages/ts-components/src/components/in-article-big-numbers/__tests__/BigNumbers.test.tsx
> +  describe('tracking', () => {
Hi **@bibicollins1**, Thanks you. UI Changes are done, updated the tests on the tracking part. Please review and suggest if you need any more changes.

2021-09-13 11:14 UTC, bibicollins1 commented on packages/ts-components/src/components/in-article-big-numbers/__tests__/BigNumbers.test.tsx
> +  describe('tracking', () => {
Tests look good thanks @Srinivasan-Ramasamy, would it be possible to add a test to show the tracking shows interactive when there is a show all button?

2021-09-13 11:17 UTC, Srinivasan-Ramasamy commented on packages/ts-components/src/components/in-article-big-numbers/__tests__/BigNumbers.test.tsx
> +  describe('tracking', () => {
Thanks @bibicollins1, Its need some more logic has to be done in unit testing.  Its more tricky one.

2021-09-14 08:28 UTC, Srinivasan-Ramasamy commented on packages/ts-components/src/components/in-article-big-numbers/__tests__/BigNumbers.test.tsx
> +  describe('tracking', () => {
Hi @bibicollins1, Good Morning.
Reg#2790 Feedback comments "Add a test to show the tracking shows interactive when there is a show all button". I've tried all the way, still facing issues to get more details to the unit test file to show interactive/static. Its needs a calculation to get clientHeight and card size -  but in unit test file not able to get all those details. Please suggest?

2021-09-14 08:50 UTC, bibicollins1 approved these changes

2021-09-14 09:34 UTC, merged