Feat/TDP 114 Timelines
newsuk/times-components pull request #2791
Opened 2021-09-14 05:40 UTC by Srinivasan-Ramasamy

Please review and give your feedback. Thanks Team,

2021-09-15 08:25 UTC, bibicollins1 commented on packages/ts-components/src/components/in-article-timelines/__tests__/Timelines.test.tsx
> +  it('should render the bullet points component', () => {
Could we add a check in these that checks an image/bullet point is rendered?

2021-09-15 08:29 UTC, bibicollins1 requested changes

2021-09-15 08:29 UTC, bibicollins1 commented on packages/ts-components/src/components/in-article-timelines/__tests__/__snapshots__/Timelines.test.tsx.snap
> +              <div
Is there meant to be <img> tags in here?

2021-09-15 08:29 UTC, bibicollins1 commented on packages/ts-components/src/components/common-styles.ts
> +  padding-bottom: 5px;
This will affect all the components that use Label, is that what Scott wanted in design review?

2021-09-20 05:35 UTC, Srinivasan-Ramasamy commented on packages/ts-components/src/components/common-styles.ts
> +  padding-bottom: 5px;
Yes Bibi, Scott was given his pixel perfect comment as per the Figma screens. So I've done the changes as per the figma.

2021-09-20 05:35 UTC, Srinivasan-Ramasamy commented on packages/ts-components/src/components/in-article-timelines/__tests__/__snapshots__/Timelines.test.tsx.snap
> +              <div
Yes Bibi, updated the test result.

2021-09-20 05:36 UTC, Srinivasan-Ramasamy commented on packages/ts-components/src/components/in-article-timelines/__tests__/Timelines.test.tsx
> +  it('should render the bullet points component', () => {
Thanks Bibi, I've added the condition.

2021-09-20 06:36 UTC, Srinivasan-Ramasamy commented on packages/ts-components/src/components/in-article-timelines/__tests__/Timelines.test.tsx
> +  it('should render the bullet points component', () => {
Please let me know if you need any more changes. Thanks a lot Bibi for the reviews.

2022-03-08 14:48 UTC, bibicollins1 submitted a review, later dismissed

2022-03-16 17:00 UTC, bibicollins1 approved these changes

2022-03-16 17:00 UTC, merged