Task/enable visual snapshots cypress
newsuk/times-components pull request #2841
Opened 2022-01-18 13:44 UTC by shubhambajpaiNUK

Description: I have taken the reference from Vinh's [PR:](https://github.com/newsuk/times-components/compare/task/TDP-778_enable_visual_snapshots?expand=1)  for enabling the cypress snapshot testing under SSR flow. 
I have worked over the flakiness of DropCap and ShareBar component in this PR. 
I am waiting for the contents to be fully loaded and disabling the cache in beforeEach segment and then added recursive function in order to retry the DropCap / Share Bar being loaded or not.

I have updated the snapshots and updated one command to updateScreenshot as a new job in package.json file.

2022-01-19 09:22 UTC, fayeez-tnl requested changes
Hey Shubham sorry for blocking the PR, let's talk through some of the changes here :)

2022-01-19 09:22 UTC, fayeez-tnl commented on packages/.env
> +GRAPHQL_TOKEN=45aea5e6-e1be-11e7-80c1-9a214cf093ae
Doesn't look like we should be checking these in?

2022-01-19 09:22 UTC, fayeez-tnl commented on packages/article-skeleton/src/article-skeleton.js
> +import { MessageContext, MessageManager } from "@times-components/message-bar";
Why is this added here?

2022-01-19 09:22 UTC, fayeez-tnl commented on packages/article-skeleton/src/article-skeleton.js
> +        <h1>{article.template}</h1>
How come you added this?

2022-01-19 09:22 UTC, fayeez-tnl commented on packages/ssr/__tests__/cypress/support/index.js
> +require("cypress-wait-until");
Why do we need this package? Can't we use cypress.wait command?

2022-01-19 09:22 UTC, fayeez-tnl commented on packages/ssr/__tests__/cypress/support/index.js
> +  cy.waitUntil(() => cy.get(path).should('be.visible') // yields <nav>
can't we wait for the selector with cy.wait(..)?

2022-01-19 09:22 UTC, fayeez-tnl commented on packages/ssr/__tests__/cypress/support/index.js
> +  cy.waitUntil(() => cy.get(path).should('have.css', 'justify-content') // yields 'sans-serif'
can't we wait for the selector with cy.wait(..)?

2022-01-19 09:22 UTC, fayeez-tnl commented on packages/ssr/__tests__/helpers/article-helper.js
> +    it.only("should match snapshots", () => {
Remove the only here :)

2022-01-19 09:22 UTC, fayeez-tnl commented on packages/ssr/__tests__/cypress/support/index.js
> +}
Let's grab some time to talk about this - I feel there may be a better way to do what you are trying to do.

2022-01-19 09:45 UTC, shubhambajpaiNUK commented on packages/ssr/__tests__/cypress/support/index.js
> +}
Sure Fayeez. Thanks for the review :)

2022-01-21 09:44 UTC, vinhlam commented on packages/.env
> +GRAPHQL_TOKEN=45aea5e6-e1be-11e7-80c1-9a214cf093ae
sorry, did i add that? it should be in the `.gitignore`

2022-01-21 10:13 UTC, bajpaijee commented on packages/.env
> +GRAPHQL_TOKEN=45aea5e6-e1be-11e7-80c1-9a214cf093ae
Thanks @vinhlam, I will update and remove the file from the PR.

2022-01-25 07:51 UTC, shubhambajpaiNUK commented on packages/ssr/__tests__/helpers/article-helper.js
> +    it.only("should match snapshots", () => {
It has been fixed

2022-01-25 07:52 UTC, shubhambajpaiNUK commented on packages/article-skeleton/src/article-skeleton.js
> +        <h1>{article.template}</h1>
I have removed the heading tag and updated the screenshots

2022-01-25 07:52 UTC, shubhambajpaiNUK commented on packages/article-skeleton/src/article-skeleton.js
> +import { MessageContext, MessageManager } from "@times-components/message-bar";
Removed

2022-01-25 09:51 UTC, fayeez-tnl approved these changes

2022-01-25 10:02 UTC, merged