Feat(TDP-760): Create article heading divider for live news
newsuk/times-components pull request #2850
Opened 2022-02-11 19:32 UTC by othetgyi

This work-in-progress PR adds the article heading divider for live news. 

[TDP-760](https://nidigitalsolutions.jira.com/browse/TDP-760)

Work completed:
-Added appropriate styling at different breakpoints
-Added logic to show different times/dates:
   -'Updated since' shows up only up to 12 hours
   -Show date for previous days

Work to be completed:
-Write unit tests
-Add knobs to Storybook stories to show different times of updates
-Add data object from ticket to packages/article-skeleton/fixtures/full-article-content.js

Screenshots of article heading divider to date:
Divider with breaking flag, time since updating and updated time:
![image](https://user-images.githubusercontent.com/50234696/153653877-2cab0aed-cb0a-4041-b76d-42cc8e76123a.png)

Divider with time since updating and updated time:
![image](https://user-images.githubusercontent.com/50234696/153657122-9fece967-b625-4ca9-b843-42bd6366d853.png)

Divider with just updated time:
![image](https://user-images.githubusercontent.com/50234696/153657244-d3819959-d038-49ef-b36b-fb615d681a2b.png)

Divider with updated time and date:
![image](https://user-images.githubusercontent.com/50234696/153657400-4342dbed-af4b-42d7-a5ab-fcae98630dae.png)

2022-02-17 10:01 UTC, takuhii approved these changes

2022-02-17 10:08 UTC, flashcheeks requested changes

2022-02-17 10:08 UTC, flashcheeks commented on packages/ts-components/package.json
> +    "date-fns": "1.28.5",
I think @adamosborne-tnl has just updated this dependancy, you might want to upgrade to `2.28.0`

2022-02-17 10:08 UTC, flashcheeks commented on packages/ts-components/src/components/article-flag/LiveArticleFlag.tsx
> +    <LiveDiamondContainer>{'\u25a0'}</LiveDiamondContainer>
Is `LiveArticleFlag.tsx` used to display the flag elsewhere in the article page? Is this icon change used across the article?

2022-02-17 10:54 UTC, bibicollins1 commented on packages/ts-components/src/components/article-flag/LiveArticleFlag.tsx
> +    <LiveDiamondContainer>{'\u25a0'}</LiveDiamondContainer>
Yeah they wanted to change it globally so all of them will have this change

2022-02-22 11:55 UTC, flashcheeks approved these changes

2022-02-22 11:57 UTC, merged