feat(TDP-1452): updated live blog schema to have live blog updates
newsuk/times-components pull request #2878
Opened 2022-03-10 11:41 UTC by adamosborne-tnl

I have the **LiveBlogPosting** schema to include the incremental **liveBlogUpdate** values in the schema. This is mostly the ArticleHeader divider data provided by these headers 
![image](https://user-images.githubusercontent.com/89213300/157654460-ecb7cd31-ce88-4169-ade5-77fccf790796.png)
There is also additional information provided by the subsequent paragraphs, images or videos included in the update.

you should be able to validate the schema at https://validator.schema.org/ by looking for the **liveBlogUpdate** data
![image](https://user-images.githubusercontent.com/89213300/157654807-0ba985b0-6256-4912-9fbf-9f939a063467.png)

2022-03-10 12:38 UTC, flashcheeks requested changes

2022-03-10 12:38 UTC, flashcheeks commented on packages/ts-components/src/components/article-header/ArticleHeader.tsx
> +  const anchorPoint = `u_${window.btoa(updated)}`;
`updated` might not be unique. maybe we can add the index value?

2022-03-10 12:38 UTC, flashcheeks commented on packages/article-skeleton/src/head.js
> +  for (let i = 0; i < article.content.length; i += 1) {
`article.content` also contains a `paywall` object that you need to parse, or has this been normalised already?

2022-03-10 13:45 UTC, adamosborne-tnl commented on packages/ts-components/src/components/article-header/ArticleHeader.tsx
> +  const anchorPoint = `u_${window.btoa(updated)}`;
Only needs to be unique enough for the page and I somewhat doubt that they would have multiple headlines to the second on the same blog page. I use the same value in the head.js for the schema so didn't want to curry the value that may not be the same elsewhere

2022-03-10 13:51 UTC, adamosborne-tnl commented on packages/article-skeleton/src/head.js
> +  for (let i = 0; i < article.content.length; i += 1) {
Hmm, only working on storybook, got any ideas on how i could check that?

2022-03-10 13:53 UTC, adamosborne-tnl commented on packages/article-skeleton/src/head.js
> +  for (let i = 0; i < article.content.length; i += 1) {
would i need to check though `content` and `paywalledContent` ?

2022-03-14 11:50 UTC, adamosborne-tnl commented on packages/article-skeleton/src/head.js
> +  for (let i = 0; i < article.content.length; i += 1) {
ok, updated for `paywall`

2022-03-14 13:13 UTC, DMackintosh-TNL commented on packages/ts-components/src/components/article-header/ArticleHeader.tsx
> +  const anchorPoint = `u_${window.btoa(updated)}`;
Should it be back ticked?

2022-03-14 13:21 UTC, adamosborne-tnl commented on packages/ts-components/src/components/article-header/ArticleHeader.tsx
> +  const anchorPoint = `u_${window.btoa(updated)}`;
yes, but that's an old line now.

2022-03-14 14:48 UTC, DMackintosh-TNL approved these changes
Looks good mate :)

2022-03-16 09:24 UTC, flashcheeks approved these changes

2022-03-16 09:48 UTC, merged