feat(TDP-1942): Integrate Times Components to NewsKit API
newsuk/times-components pull request #2946
Opened 2022-05-19 09:57 UTC by DMackintosh-TNL

### Description
To support the implementation of “Today’s <section>" rail driven by the Product Platforms ‘Recommendations Engine’, integrate Times Components with the NewsKit API.

I have raised this PR as I don't feel the work in finished yet and would like some steer on a) if I am going in the right directions, and b) what the next steps for me are?

The data isn't "complete" by any stretch of the term, but all the hooks are in place, but could be subject to change once the work has been completed on the API.

It's also in a weird place in Storybook: Typescript Components > In Article > Newsletter Puffs > Recommended Articles

I'm just after feedback at the moment...

[TDP-1942](https://nidigitalsolutions.jira.com/browse/TDP-1942)

### Checklist
- [x] Have you done any manual testing?
- [ ] Does it have automated tests?
- [ ] Do you need any other PRs merged before this (if so please list)?
- [ ] Do you need to update the README/Runbook
- [ ] Have you checked for [accessibility](https://nidigitalsolutions.jira.com/wiki/spaces/TNLDigital/pages/3898048523/Accessibility+Dev+Guide#Checklist)?

### Screenshots (if appropriate):
<img width="1440" alt="Screenshot 2022-05-19 at 10 56 36" src="https://user-images.githubusercontent.com/94699701/169266985-ca935027-ad6b-4fd7-8d0e-0878efca0b5e.png">

2022-05-20 17:09 UTC, SunshineEleda requested changes
Looks good, just left a few comments. Also with my ticket I will override the component you have made.

2022-05-20 17:09 UTC, SunshineEleda commented on packages/provider-queries/src/recommended_articles.graphql
> +}
I've been working on the ui ticket and based on what I saw in the screenshot we only need the image, id, shortidentifier, headline, url, slug. So I'm not sure we will need all of the other information. At the moment just missing the shortidentifier from your query

2022-05-20 17:09 UTC, SunshineEleda commented on packages/provider/src/recommended-articles.js
> +export default connectGraphql(recommendations);
Can a test be added for this please?

2022-05-20 17:53 UTC, DMackintosh-TNL commented on packages/provider-queries/src/recommended_articles.graphql
> +}
No, totally agree, the query retrieves "everything" at the moment as I didn't know what was required, I can re-write it though ;)

2022-05-20 17:53 UTC, DMackintosh-TNL commented on packages/provider/src/recommended-articles.js
> +export default connectGraphql(recommendations);
Maaaaaaybe... Sure, not a problem..

2022-05-20 18:04 UTC, DMackintosh-TNL commented on packages/provider-queries/src/recommended_articles.graphql
> +}
Might be worth noting that `shortidentifier` doesn't exist yet, as the work still needs to be done to make the feed better

2022-05-23 13:00 UTC, DMackintosh-TNL commented on packages/provider/src/recommended-articles.js
> +export default connectGraphql(recommendations);
As discussed, tests no longer required...

2022-05-23 13:16 UTC, SunshineEleda approved these changes

2022-05-23 14:08 UTC, othetgyi reviewed
Nice work, Darren! This looks very cleanly done. 

Because of the linting errors, I'm wondering if recommended_articles.graphql needs to have  formatter run on it? Also, to meet the test coverage threshold, do you need a unit test for the RecommendedArticles.tsx component?

2022-05-23 15:51 UTC, DMackintosh-TNL commented
> Nice work, Darren! This looks very cleanly done.
> 
> Because of the linting errors, I'm wondering if recommended_articles.graphql needs to have formatter run on it? Also, to meet the test coverage threshold, do you need a unit test for the RecommendedArticles.tsx component?

I'll take a look ;)

2022-05-25 11:17 UTC, othetgyi approved these changes

2022-05-25 12:23 UTC, merged