TDP-1825 Removed year and added GMT BST to timestamp
newsuk/times-components pull request #2958
Opened 2022-05-31 13:53 UTC by DMackintosh-TNL

### Description
New logic for the timestamp on the Article Divider: Examples below;

All timestamps shall remain the same with the same logic barring the following exceptions

- The 24hr timestamp shall display the correct timezone for non-UK viewers of the page

Currently 12.55 BST OR in winter 12.55 GMT
**Note:** This logic should already exist and be in use for international readers on the publication date

The date stamp logic shall remain as-is, the only change is that we are removing the year

Currently: mmm dd yyyy (May 31 2022)
Should be: mmm dd (May 31)

[TDP-1825](https://nidigitalsolutions.jira.com/browse/TDP-1825)

### Checklist
- [x] Have you done any manual testing?
- [ ] Does it have automated tests?
- [ ] Do you need any other PRs merged before this (if so please list)?
- [ ] Do you need to update the README/Runbook
- [ ] Have you checked for [accessibility](https://nidigitalsolutions.jira.com/wiki/spaces/TNLDigital/pages/3898048523/Accessibility+Dev+Guide#Checklist)?

Screenshots (from StoryBook):
**GMT**
<img width="1121" alt="Screenshot 2022-05-31 at 14 42 28" src="https://user-images.githubusercontent.com/94699701/171190048-a50dc37e-dc01-44ee-988d-b589f5b2b117.png">

**BST**
<img width="1116" alt="Screenshot 2022-05-31 at 14 42 13" src="https://user-images.githubusercontent.com/94699701/171190138-e62b788e-64ea-4bf5-84fe-a13c6f3ec6b0.png">

2022-05-31 13:58 UTC, flashcheeks requested changes

2022-05-31 13:58 UTC, flashcheeks commented on packages/ts-components/src/components/article-header/ArticleHeader.tsx
> +            {format(parsedDate, 'h.mmaaa z')}
Will this display the timezone for all users not just non-UK users?

2022-05-31 14:36 UTC, othetgyi commented on packages/ts-components/src/components/article-header/ArticleHeader.tsx
>    // parse,
I noticed in other PRs there are some commented out imports, but wasn't sure why we need them?

2022-05-31 14:37 UTC, othetgyi commented on packages/ts-components/src/components/article-header/ArticleHeader.tsx
>    // zonedTimeToUtc,
Same comment as above

2022-05-31 14:48 UTC, DMackintosh-TNL commented on packages/ts-components/src/components/article-header/ArticleHeader.tsx
>    // parse,
Removed

2022-06-01 10:27 UTC, DMackintosh-TNL commented on packages/ts-components/src/components/article-header/ArticleHeader.tsx
> +            {format(parsedDate, 'h.mmaaa z')}
Works now, this might be suitable for moving to UTILS, but that is out of scope for this story :)

2022-06-01 10:40 UTC, othetgyi approved these changes

2022-06-07 11:35 UTC, flashcheeks approved these changes

2022-06-07 13:55 UTC, merged