Feat/tdp 2202 integrate new openweb commenting endpoint
newsuk/times-components pull request #3046
Opened 2022-07-22 16:48 UTC by SunshineEleda

2022-07-25 14:21 UTC, flashcheeks requested changes

2022-07-25 14:21 UTC, flashcheeks commented on packages/article-comments/src/comment-login.js
>  const executeSSOtransaction = (isReadOnly, callback) => {
You can also remove the property `isReadOnly`

2022-07-25 15:01 UTC, SunshineEleda commented on packages/article-comments/src/comment-login.js
>  const executeSSOtransaction = (isReadOnly, callback) => {
I have added it back in because this change has affected the callback function because it is passed in second

2022-07-25 15:26 UTC, othetgyi approved these changes

2022-07-26 08:33 UTC, othetgyi commented on packages/article-comments/src/comments.js
> +        executeSSOtransaction(isSpotAccountReadOnly, () => {})
This doesn't error if you're passing two arguments into it but have defined the function to only accept one?

2022-07-26 09:14 UTC, othetgyi approved these changes
LGTM!

2022-07-26 09:49 UTC, flashcheeks approved these changes

2022-07-26 09:57 UTC, merged