feat(TDP-2203): Reauthenticate users to real name commenting
newsuk/times-components pull request #3131
Opened 2022-08-16 10:25 UTC by othetgyi

2022-08-16 16:36 UTC, SunshineEleda commented on packages/article-comments/src/utils.js
> +
I recall CPS saying we don't need to remove the local storage spotim stuff anymore. You just need to fire the executeSSOTransaction if there is not a `realNameToken` and this should take care of that.

2022-08-16 16:36 UTC, SunshineEleda commented on packages/article-comments/src/comments.js
> +import executeSSOtransaction, { setNewUserToken } from "./comment-login";
You won't need to import `setNewUserToken` here if you just call it in the `executeSSOTransaction` function in `comment-login.js`

2022-08-17 16:38 UTC, bibicollins1 reviewed
Functionally looks good to me, just wondering whether the naming could be improved? Find myself getting a bit confused with the shouldUserReauthenticate/shouldReauthenticateUser. Saying that I don't yet have a suggestion that would be better but will have a think and maybe chat about it tomorrow?

2022-08-18 06:00 UTC, gczene approved these changes

2022-08-18 08:38 UTC, SunshineEleda requested changes

2022-08-18 08:38 UTC, SunshineEleda commented on packages/article-comments/src/comments.js
> +          const shouldUserReauthenticate = shouldReauthenticateUser();
With what @bibicollins1  said I think it might make it less confusing to rename `shouldUserReauthenticate` to `shouldReauthenticateUser` 

https://github.com/newsuk/times-components/pull/3131#pullrequestreview-1076079284

2022-08-18 08:48 UTC, SunshineEleda requested changes

2022-08-18 08:48 UTC, SunshineEleda commented on packages/article-comments/src/comment-login.js
> +    setNewUserToken();
Also can we put this behind the feature flag `enableRealNameCommenting`

2022-08-18 08:48 UTC, SunshineEleda commented on packages/article-comments/src/comments.js
> +          }
Can we put this behind the feature flag enableRealNameCommenting

2022-08-18 09:47 UTC, othetgyi commented
> Functionally looks good to me, just wondering whether the naming could be improved? Find myself getting a bit confused with the shouldUserReauthenticate/shouldReauthenticateUser. Saying that I don't yet have a suggestion that would be better but will have a think and maybe chat about it tomorrow?

@bibicollins1 I've removed the shouldUserReauthenticate variable, hopefully that makes it less confusing.

2022-08-18 10:19 UTC, othetgyi commented
I've added the "DO NOT MERGE" label until the code freeze on Times Components is over and the big React Native PR has been merged in and tested.

2022-08-18 14:53 UTC, SunshineEleda commented on packages/article-comments/src/comments.js
> +          }
It would be a bit cleaner to do something like this since the executeSSoTransaction will fire regardless ```suggestion
          if (isFeatureFlagEnabled) {
            shouldReauthenticateUser()
            }

            executeSSOtransaction(() => {});
          
```

2022-08-18 14:58 UTC, SunshineEleda commented on packages/article-comments/src/utils.js
> +  }
Based on [this](https://github.com/newsuk/times-components/pull/3131#discussion_r949245978) you could change this to:


```suggestion
  if (isUsingRealNameCommenting) return 
```

2022-08-18 14:58 UTC, SunshineEleda commented on packages/article-comments/src/utils.js
> +  return true;
And then you can get rid of this since we don't need this function to return a boolean anymore

2022-08-18 15:36 UTC, SunshineEleda commented on packages/article-comments/__tests__/web/shared.web.test.js
> +  });
Can also get rid of this since it's not being used for anything

2022-08-19 14:20 UTC, SunshineEleda approved these changes

2022-08-25 16:47 UTC, merged