fix(TDP-2475): Add event listener to real name commenting reauthentication
newsuk/times-components pull request #3140
Opened 2022-09-06 12:32 UTC by othetgyi

This PR adds another event listener to real name commenting reauthentication that will check for the localStorage token dropped when then user previously logged into commenting.

2022-09-06 13:04 UTC, flashcheeks requested changes

2022-09-06 13:04 UTC, flashcheeks commented on packages/article-comments/src/comments.js
> +        executeSSOtransaction(() => {});
Call to `executeSSOtransaction()` needs to be inside the conditional

2022-09-06 13:04 UTC, flashcheeks commented on packages/article-comments/src/comments.js
> +        if (realNameCommentingCheck) {
Can you check your logic here. When the user does not have a localStorage value we should be reauthenticating.

2022-09-06 17:27 UTC, SunshineEleda commented on packages/article-comments/src/comments.js
> +      "enableReauthentication"
Would be good to make it more explicit what it is i.e. `enableRealNameReauthentication`

2022-09-07 11:03 UTC, SunshineEleda approved these changes

2022-09-07 11:04 UTC, merged