feat(TMST-626): Puzzle Card component
newsuk/times-components pull request #3333
Opened 2023-04-26 07:52 UTC by suneethanagella

[TMST-626](https://nidigitalsolutions.jira.com/browse/TMST-626)

**Description**

- created Puzzle card component using Newskit components
- Included Puzzle flag component inside puzzle card
- wrote unit tests for the puzzle component
- wrote a story for the puzzle component 

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/105289286/234506454-88ab84e4-4aaf-418e-ae84-cfe767acd463.png">

2023-04-28 07:04 UTC, jasminaj0 requested changes

2023-04-28 07:04 UTC, jasminaj0 commented on packages/ts-newskit/src/components/puzzles/puzzle-card/index.tsx
> +    <StyledCard key={puzzle.id} href={puzzle.url}>
When using `CardComposable`, I think you should also use `CardMedia `and `CardActions `when creating card. Please check with Mike about this, which component to use for any card section

2023-04-28 07:04 UTC, jasminaj0 commented on packages/ts-newskit/src/components/puzzles/puzzle-card/PuzzleCard.stories.mdx
> +The `PuzzleCard` component is used to display puzzles date cards.
or just puzzle card

2023-04-28 13:01 UTC, jasminaj0 approved these changes

2023-04-28 13:28 UTC, douglasmik commented on packages/ts-newskit/src/components/puzzles/puzzle-card/PuzzleCard.stories.mdx
> +`<PuzzleCard data={ puzzles.list[0] }/>`
may be better to deconstruct this for clarity

2023-04-28 13:34 UTC, douglasmik commented on packages/ts-newskit/src/components/puzzles/puzzle-card/assets/PuzzlePlaceholder.tsx
> +        fill="#FFEED9"
`currentcolor` would be better, particularly if there's any chance that this may be used elsewhere?

2023-04-28 13:35 UTC, douglasmik commented on packages/ts-newskit/src/components/puzzles/puzzle-card/assets/PuzzlePlaceholder.tsx
> +          fill="white"
would this be better being transparent, or using a token value?

2023-04-28 13:37 UTC, douglasmik commented on packages/ts-newskit/src/components/puzzles/puzzle-card/index.tsx
> +  const imageUrl = data.image && data.image.src ? data.image.src : '';
could we use optional chaining?
e.g. `data.image?.src || ''`

2023-04-28 13:38 UTC, douglasmik commented on packages/ts-newskit/src/theme/puzzles-web-light/style-presets.ts
> +    borderRadius: '2px',
token value?

2023-04-28 13:38 UTC, douglasmik commented on packages/ts-newskit/src/theme/puzzles-web-light/style-presets.ts
> +    borderRadius: '2px',
token value?

2023-04-28 13:42 UTC, douglasmik commented on packages/ts-newskit/src/components/puzzles/puzzle-card/index.tsx
> +        },
should we be controlling dimensions here? Assuming that these components should basically fill width of their containers. If put in a grid, for example, it would just fill the allotted space.

2023-04-28 13:42 UTC, douglasmik commented on packages/ts-newskit/src/components/puzzles/puzzle-card/index.tsx
> +                }
as above

2023-04-28 13:47 UTC, ibrahim-kurhan commented on packages/ts-newskit/src/theme/puzzles-web-light/style-presets.ts
> +    borderRadius: '2px',
I have probably missed it but do we have token value for 2px?

2023-04-28 13:49 UTC, douglasmik commented on packages/ts-newskit/src/theme/puzzles-web-light/style-presets.ts
> +    borderRadius: '2px',
as above

2023-04-28 13:53 UTC, ibrahim-kurhan commented on packages/ts-newskit/src/theme/puzzles-web-light/style-presets.ts
> +    borderRadius: '2px',
yeap here is the link for it https://newskit.co.uk/theme/foundation/borders/#border-radius

2023-05-02 11:30 UTC, douglasmik commented on packages/ts-newskit/src/components/puzzles/puzzle-card/index.tsx
> +  const imageUrl = image!.src || '';
Think this needs to be `image?.src || '';` with the `?` instead of the `!`, as if image object is not passed it would be `null` where the `!.` operator is taking it as a 'non-null' value

2023-05-02 11:39 UTC, douglasmik approved these changes

2023-05-02 12:19 UTC, merged