feat(TMRX-1492): hide top image in lead 3
newsuk/times-components pull request #3533
Opened 2023-09-14 15:27 UTC by yukiinasawa

### Description

Hide top image in lead 3 

NOTE: in the ticket, Himesh mentioned that we hide the top image in 'md' size but if you see the third column means that screen size is either 'lg' or 'xl' so I'll confirm when design review - I think he meant to say 'lg'

[TMRX-1492](https://nidigitalsolutions.jira.com/browse/TMRX-1492)

### Checklist

- [ ] Have you done any manual testing?
- [ ] Does it have automated tests?
- [ ] Do you need any other PRs merged before this (if so please list)?
- [ ] Do you need to update the README/Runbook
- [ ] Have you checked for [accessibility](https://nidigitalsolutions.jira.com/wiki/spaces/TNLDigital/pages/3898048523/Accessibility+Dev+Guide#Checklist)?

### Screenshots (if appropriate):

<img width="997" alt="Screenshot 2023-09-14 at 16 23 38" src="https://github.com/newsuk/times-components/assets/139121277/645db5ee-850e-47c8-8ea1-bc0f332745bc">

2023-09-14 15:34 UTC, milanharia-tm approved these changes

2023-09-14 15:38 UTC, ibrahim-kurhan requested changes
your approach will remove the top image from all slices I think we just need remove it from the lead story 3

2023-09-14 16:18 UTC, yukiinasawa commented
Thanks @ibrahim-kurhan 👍 updated!

2023-09-15 06:11 UTC, ibrahim-kurhan commented on packages/ts-newskit/src/slices/lead-story-3/index.tsx
> +  });
would it be cleaner to implement it like this   
```
const modifedArticles = articles.map(article => ({
    ...article,
    imageRight: currentBreakpoint === 'xl',
    hideImage: currentBreakpoint === 'lg'
}));
```

2023-09-15 08:50 UTC, ibrahim-kurhan approved these changes

2023-09-15 10:20 UTC, merged